/**
 * hibari_comparison_data.js
 *
 * Pre-computed pitch class distribution comparison:
 *   original hibari  vs.  best generated (FC + continuous, JS=0.0004 ★)
 *
 * Generated by: tda_pipeline/gen_hibari_viz_data.py (+ pretty_midi analysis)
 * Date: 2026-04-15
 */

window.HIBARI_COMPARISON_DATA = {
  pc_names: ['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'],

  original: {
    label:   'hibari (original)',
    dist:    [0.152542, 0.0, 0.118644, 0.0, 0.186441, 0.101695, 0.0,
              0.152542, 0.0, 0.169492, 0.0, 0.118644],
    n_notes: 3953
  },

  generated: {
    label:   'Generated — FC + continuous (JS=0.0004 ★)',
    dist:    [0.150497, 0.0, 0.122231, 0.0, 0.194041, 0.090145, 0.0,
              0.152788, 0.0, 0.175707, 0.0, 0.114591],
    n_notes: 1309
  },

  js_pc:   0.000274,   // pitch class 기준 JS
  js_note: 0.0004,     // note (pitch×dur) 기준 JS — 논문 보고 수치
  model:   'FC + continuous activation',
  config:  'Tonnetz (α=0.0, ow=0.3) · per-cycle τ_c · T=3.0'
};
